# Generated by Django 4.2.1 on 2023-07-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
